<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Alpha Furniture')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/layout.css?v=2'))
            ->prependStylesheet($this->basePath('bootstrap-4.0.0/css/bootstrap.min.css'))
        ?>

    </head>
    <body>

        <nav id="navbar" class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#"><img src="<?= $this->basePath('img/logo-small.png') ?>" height="40px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact Us</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ap-secondary-menu-sign-in">
                            <a class="nav-link ap-secondary-menu-sign-in-link" href="#">Sign In</a>
                        </li>
                        <li class="nav-item ap-secondary-menu-sign-up">
                            <a class="nav-link ap-secondary-menu-sign-up-link" href="#">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="af-navbar-full">
            <div class="af-navbar-top-container">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3 ap-brand-container">
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/logo-full.png') ?>" height="60px" /></a>
                        </div>
                        <div class="col-sm-9 ap-navbar-container">
                            <div class="ap-navbar-top">
                                <div class="ap-top-menu-contact">CONSUMER HOTLINE <span>+1 212 123 4567</span></div>
                                <div class="ap-top-menu-sign-in">
                                    <a class="ap-top-menu-catalog-link" href="">New 2018 Catalog</a>
                                    <a class="ap-top-menu-sign-in-link" href="#">Sign In</a>
                                    <a class="ap-top-menu-sign-up-link" href="#">Register</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="af-navbar-bottom-container">
                <div class="container">
                    <div class="af-navbar-main-menu">
                        <nav class="nav d-flex">
                            <a class="af-menu-item" href="#">Home</a>
                            <a class="af-menu-item" href="#">About Us</a>
                            <a class="af-menu-item" href="#">Catalog</a>
                            <a class="af-menu-item" href="#">Contact Us</a>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <main role="main">

            <?= $this->content ?>

            <!-- FOOTER -->

            <div class="ap-footer-info">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4 ap-footer-info-left">
                            <h4>Navigation</h4>
                            <ul class="ap-footer-info-nav">
                                <li><a href="">Home</a></li>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Catalog</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                            <ul class="ap-footer-info-sign-in">
                                <li><a href="" class="ap-footer-info-sign-in-link">Sign In</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4 ap-footer-info-middle">
                            <form>
                                <h4>Contact Us</h4>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Name" />
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Message"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </form>
                        </div>
                        <div class="col-sm-4 ap-footer-info-right">
                            <h4>Our Location</h4>
                            <p>198 West 60 New Street<br />New York, NY 11234</p>
                            <p><strong>E-mail:</strong> info@example.com</p>
                            <p><strong>Phone:</strong> 703.172.3412</p>
                            <p><strong>Fax:</strong> 703.585.5948</p>
                        </div>
                    </div>
                </div>
            </div>

            <footer>
                <div class="container">
                    <p class="float-right"><a href="#" class="af-back-to-top" id="af-back-to-top">Back to top</a></p>
                    <p>&copy; <?= date('Y') ?> Alpha Furniture.</p>
                </div>
            </footer>
        </main>






        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/layout.js?v=2'))
            ->prependFile($this->basePath('bootstrap-4.0.0/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </body>
</html>
