<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Alpha Furniture')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/layout.css'))
            ->prependStylesheet($this->basePath('bootstrap-4.0.0/css/bootstrap.min.css'))
        ?>

    </head>
    <body>

        <nav id="navbar" class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#"><img src="<?= $this->basePath('img/logo-small.png') ?>" height="50px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="af-navbar-full">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 ap-brand-container">
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/logo-full.png') ?>" height="120px" /></a>
                    </div>
                    <div class="col-sm-9 ap-navbar-container">
                        <div class="ap-navbar-top">
                            <ul class="navbar-nav">
                                <li class="nav-item ap-top-menu-contact">+1 347 575 6340</li>
                                <li class="nav-item ap-top-menu-sign-in"><a href="#">Sign In</a></li>
                            </ul>
                        </div>
                        <div class="ap-navbar-main">
                            <ul class="navbar-nav">
                                <li class="nav-item active"><a href="#">Home</a></li>
                                <li class="nav-item"><a href="#">About Us</a></li>
                                <li class="nav-item"><a href="#">Catalog</a></li>
                                <li class="nav-item"><a href="#">Contact Us</a></li>
                            </ul>
                            <div style="clear: both;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <main role="main">


            <?= $this->content ?>

            <!-- FOOTER -->
            <footer class="container">
                <p class="float-right"><a href="#">Back to top</a></p>
                <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
            </footer>
        </main>






        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/layout.js'))
            ->prependFile($this->basePath('bootstrap-4.0.0/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </body>
</html>
