<?= $this->headLink()->appendStylesheet('/css/home.css?v=1') ?>
<?php $this->inlineScript()->prependFile('/js/home.js?v=1') ?>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="first-slide" src="<?= $this->basePath('img/slide01.jpg') ?>" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="second-slide" src="<?= $this->basePath('img/slide02.jpg') ?>" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="third-slide" src="<?= $this->basePath('img/slide03.jpg') ?>" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container ap-shipping-info">
    <h1>Alpha Furniture - A Sense Of Comfort To Your Life</h1>
    <div class="row">
        <div class="col-sm-4">
            <h3>FREE SHIPPING</h3>
            <p>Quickly and simply deliver the goods anywhere in the world.</p>
        </div>
        <div class="col-sm-4">
            <h3>RETURN OF GOODS</h3>
            <p>You can return any item withing 30 days with no reason and get full refund.</p>
        </div>
        <div class="col-sm-4">
            <h3>SATISFACTION GUARANTEED</h3>
            <p>We will refund you any goods if you do not like it or it will be defective.</p>
        </div>
    </div>
</div>

<div class="container ap-category-container">
    <div class="row">
        <div class="col-sm-6">
            <div class="ap-category-item ap-category-01">
                <img class="img-fluid" src="<?= $this->basePath('img/category01.jpg') ?>" />
            </div>
        </div>
        <div class="col-sm-6">
            <div class="ap-category-item ap-category-02">
                <img class="img-fluid" src="<?= $this->basePath('img/category02.jpg') ?>" />
            </div>
        </div>
    </div>
</div>

<div class="container ap-popular-products">
    <h2>Popular Products</h2>
    <div class="row">
        <div class="col-sm-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/category01.jpg') ?>" />
            </div>
        </div>
        <div class="col-sm-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/category02.jpg') ?>" />
            </div>
        </div>
        <div class="col-sm-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/category01.jpg') ?>" />
            </div>
        </div>
        <div class="col-sm-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/category02.jpg') ?>" />
            </div>
        </div>
    </div>
</div>