<?= $this->headLink()->appendStylesheet('/css/home.css?v=2') ?>
<?php $this->inlineScript()->prependFile('/js/home.js?v=2') ?>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="first-slide" src="<?= $this->basePath('img/slide01.jpg') ?>" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="second-slide" src="<?= $this->basePath('img/slide02.jpg') ?>" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="third-slide" src="<?= $this->basePath('img/slide03.jpg') ?>" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container ap-shipping-info">
    <h1>Alpha Furniture - A Sense Of Comfort To Your Life</h1>
    <div class="row">
        <div class="col-sm-4">
            <h3 class="af-message-catalog">New 2018 Catalog</h3>
            <p>Coming soon!</p>
        </div>
        <div class="col-sm-4">
            <h3 class="af-message-order">Online Ordering</h3>
            <p>Coming soon!</p>
        </div>
        <div class="col-sm-4">
            <h3 class="af-message-store">Want To Carry Our Products?</h3>
            <p><a href="" class="btn btn-md btn-outline-secondary">SIGN UP AS A RETAILER</a></p>
        </div>
    </div>
</div>


<div class="container ap-category-container">
    <div class="row">
        <div class="col-md-4">
            <div class="ap-category-item ap-category-01">
                <img class="img-fluid" src="<?= $this->basePath('img/banner01.jpg') ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="ap-category-item ap-category-02">
                <img class="img-fluid" src="<?= $this->basePath('img/banner02.jpg') ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="ap-category-item ap-category-02">
                <img class="img-fluid" src="<?= $this->basePath('img/banner03.jpg') ?>" />
            </div>
        </div>
    </div>
</div>


<div class="container ap-popular-products">
    <h2>What's New - Introducing New Products From Our Catalog</h2>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_01_small.jpg') ?>" />
                <h3>SIESTA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_02_small.jpg') ?>" />
                <h3>LYON</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_03_small.jpg') ?>" />
                <h3>POLO</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_04_small.jpg') ?>" />
                <h3>CLARA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_05_small.jpg') ?>" />
                <h3>MUNIF</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_06_small.jpg') ?>" />
                <h3>DUAA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_07_small.jpg') ?>" />
                <h3>HALA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_08_small.jpg') ?>" />
                <h3>SONYA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_09_small.jpg') ?>" />
                <h3>JENNIFER</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_10_small.jpg') ?>" />
                <h3>RANA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_11_small.jpg') ?>" />
                <h3>TALYA</h3>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="ap-product-item">
                <img class="img-fluid" src="<?= $this->basePath('img/items/item_12_small.jpg') ?>" />
                <h3>ADAM</h3>
            </div>
        </div>
    </div>
</div>